version: '3.1'
services:
    app:
        image: node:18-alpine
        restart: always
        working_dir: /usr/app/gogoro_demo
        volumes:
            - ../:/usr/app/gogoro_demo
            - ./config:/usr/app/config
        ports:
            - 3003:3003
        command: sh -c "npm install && npm start"

    mariadb:
        image: mariadb:latest
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: scott_tsao
            MYSQL_PASSWORD: abcd1234
        volumes:
            - ./mysql-dump:/docker-entrypoint-initdb.d/
