version: '3.1'
services: 
    mariadb:
        image: mariadb:latest
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: scott_tsao
            MYSQL_PASSWORD: abcd1234
        volumes:
            - ./mysql-dump:/docker-entrypoint-initdb.d/
